version: "3.11"

services:
  medication_request_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      postgresql:
        condition: service_healthy
    environment:
      SQLALCHEMY_DATABASE_URL: ${URL_DATABASE}
    container_name: FastAPI_Medication

  postgresql:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: medication_requests
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d medication_requests"]
      interval: 10s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: "admin@gmail.com"
      PGADMIN_DEFAULT_PASSWORD: "admin"
    ports:
      - 5050:80
    depends_on:
      - postgresql
      - medication_request_api

volumes:
  postgres_data:
